server:
  port: 8003
spring:
  application:
    name: service-two #服务名，也就是消费客户端需要的service id
#  zipkin:
#    base-url: http://localhost:9411 #zipkin server地址
#  sleuth:
#    sampler:
#      percentage: 1.0 #即100%的概率将链路的数据上传给Zipkin Server，默认为0.1
#  rabbitmq:   #配置rabbitmq
#    host: 192.168.50.234
#    port: 5763
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
#      defaultZone: http://user:123456@localhost:1111/eureka/  #指定服务注册中心的地址
      defaultZone: http://user:123456@localhost:1111/eureka/  #指定服务注册中心的地址，注册中心需要认证时添加用户名和密码
## 注册中心集群时使用
#      defaultZone: http://peer2:3333/eureka/  #指定服务注册中心的地址

