#基本路由功能
spring:
  application:
    name: eureka-zuul
#  zipkin:
#    base-url: http://localhost:9411 #zipkin server地址
#  sleuth:
#    sampler:
#      percentage: 1.0 #即100%的概率将链路的数据上传给Zipkin Server，默认为0.1
#  rabbitmq:   #配置rabbitmq
#    host: 192.168.50.234
#    port: 5763
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 5000

zuul:
  routes:
    serviceoneapi:
      path: /serviceoneapi/**
      serviceId: service-one #使用serviceId可以应用负载均衡策略，如果不使用负载均衡，可以指定url：http://localhost:8001
    ribbonapi:
      path: /ribbonapi/**
      serviceId: service-ribbon
    feignapi:
      path: /feignapi/**
      serviceId: service-feign
  ignored-patterns: /ribbonapi/hello/** #忽略该路由，不希望被Api网关进行路由



#  prefix: /v1 #添加版本号，这样访问的路径就为 http://localhost:5000/v1/serviceoneapi/hello
#    hiapi:
#      path: /hiapi/**
#      serviceId: hiapi-v1 #不使用Eureka服务注册列表，使用自己配置的列表，做负载均衡
#
#ribbon:
#  eureka:
#    enabled: false
#
#hiapi-v1:
#  ribbon:
#    listOfServers: http://localhost:1234, http://localhost:5678